name: Lupus
targets:
  Lupus:
    platform: iOS
    type: application
    deploymentTarget: "12.0"
    sources:
      - Lupus/
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.homiedev.Lupus